
#include <Arduino.h>
#include <WiFi.h>
#include <HTTPClient.h>
#include <AsyncTCP.h>
#include <ESPAsyncWebServer.h>
#include <WiFiClient.h>
#include <time.h>
#include "types.h"
#include "LittleFS.h"
#include <ArduinoJson.h>

// build_info.h is generated by build-firmware.sh. Arduino IDE users who skip
// the script get the compiler __DATE__/__TIME__ fallback instead.
#if __has_include("build_info.h")
  #include "build_info.h"
#endif
#ifndef FIRMWARE_BUILD_TIME
  #define FIRMWARE_BUILD_TIME __DATE__ " " __TIME__
#endif
#ifndef FIRMWARE_GIT_COMMIT
  #define FIRMWARE_GIT_COMMIT "unknown"
#endif

// ESP32 GPIO pin definitions
#define GPIO_ADC_PRESSURE 34

#define GPIO_IRRIGATIONPUMP 14
#define GPIO_WELLPUMP 27

#define GPIO_VALVE_1 25
#define GPIO_VALVE_2 26
#define GPIO_VALVE_3 32
#define GPIO_VALVE_4 33
#define GPIO_VALVE_5 13

#define GPIO_WATERLEVEL_EMPTY 19
#define GPIO_WATERLEVEL_1 18
#define GPIO_WATERLEVEL_2 5
#define GPIO_WATERLEVEL_3 17
#define GPIO_WATERLEVEL_FULL 16

#define GPIO_WIFI_LED 21
#define GPIO_WELLPUMP_LED 22
#define GPIO_IRRIGATIONPUMP_LED 23

#define RELAIS_ON LOW
#define RELAIS_OFF HIGH

#define WIFI_STATUS_DISCONNECTED 0
#define WIFI_STATUS_CONNECTING 1
#define WIFI_STATUS_WAITING_FOR_NTP 2
#define WIFI_STATUS_NTP_ACTIVE 3

#define MY_NTP_SERVER "at.pool.ntp.org"
#define MY_TZ "CET-1CEST-2,M3.5.0/02:00:00,M10.5.0/03:00:00"  // https://remotemonitoringsystems.ca/time-zone-abbreviations.php

#define STATUS_UPDATE_ALL 255
#define STATUS_UPDATE_WELLPUMP 1
#define STATUS_UPDATE_IRRIGATIONPUMP 2
#define STATUS_UPDATE_RSSI 4
#define STATUS_UPDATE_TIME 8
#define STATUS_UPDATE_WATERPRESSURE 16
#define STATUS_UPDATE_WATERLEVEL 32
#define STATUS_UPDATE_CYCLE 64
#define STATUS_UPDATE_ERROR 128

#define MAX_ERROR_LENGTH 300

char *error = NULL;
uint32_t heapAfterSetup = 0;
bool wrongConfig = true;
#define MAX_PENDING_VALVES 50
volatile uint8_t pendingValves[MAX_PENDING_VALVES + 1] = { 0 };  // [0] = count, [1..n] = valve indexes

void setup() {

  // Setup console output
  Serial.begin(115200);
  Serial.println("\n\n\n\n");

  if(!LittleFS.begin(true)) {
    Serial.println(F("An error has occurred on mounting LittleFS"));
    return;
  }

  // load parameters
  if (!readConfiguration()) {
    return;
  }
  wrongConfig = false;

  // Initialize NTP for current time and Wifi
  setupWifi();

  // Initialize water pumps and valves
  setupIrrigationPump();
  setupWellPump();
  setupWaterLevel();
  setupPressureControl();
  setupValves();

  // Initialize cycle processing
  setupCycles();

  heapAfterSetup = ESP.getFreeHeap();

}

// application status
unsigned long previousTime = 0;
uint8_t interval = 0;
uint8_t wifiStatus = WIFI_STATUS_DISCONNECTED;
uint8_t lastMinute = 0;
uint8_t lastSecond = 0;
time_t now = 0;                     // this are the seconds since Epoch (1970) - UTC
tm tm_now;                          // the structure tm holds time information in a more convenient way

void loop() {

  // process data during OTA
  doOTAifActive();

  if (wrongConfig) {
    return;
  }

  // ignore loop execution more often than LED blink interval (1/8 second)
  unsigned long currentMillis = millis();
  if (currentMillis < previousTime) { // handle overflow
    previousTime = currentMillis;
    return;
  }
  if (currentMillis - previousTime < 125) {
    return;
  }
  previousTime = currentMillis;

  // track seconds based on LED blink interval (8 times = 1 second)
  ++interval;
  interval = interval % 8;
  if (interval == 0) { // every second

    // 1. check current water level
    updateWaterLevel();

    // 2. check current water pressure
    updateWaterPressure();

    // 3. control irrigation pump immediately
    controlIrrigationPump();

    // 4. control well pump (seconds granularity — needed for prompt response to
    //    FULL detection and overfill timing). tickWellPumpOverfill is invoked
    //    from inside controlWellPump's flow indirectly via the same per-second
    //    cadence, so the dedicated call below covers the countdown decrement.
    controlWellPump();
    tickWellPumpOverfill();

    if (now != 0) {  // wait for first NTP update
      time(&now);    // this function calls the NTP server only every hour
      localtime_r(&now, &tm_now);
    } else if (wifiStatus == WIFI_STATUS_DISCONNECTED) { // no Wifi connected on setup
      activateWifi();
    }

    if (tm_now.tm_min != lastMinute) { // every minute
      lastMinute = tm_now.tm_min;
      printTime(now);

      // Cheap no-op once per day after the first compute; we need it to run at
      // least once after NTP becomes available, and again across the day-change
      // boundary, so the per-minute cadence is the natural fit.
      recomputeSunTimes();

      // 5. do irrigation cycles
      checkForActiveCycles();

      // 6. switch valves according to current cycle
      switchValves();

      // reactive Wifi if connection lost
      if (wifiStatus == WIFI_STATUS_DISCONNECTED) {
        activateWifi();
      }

    }

    // switch valves if mode changed via REST API
    handleManualValveChanges();

    // every 30 seconds send update to clients to keep SSE connection alive
    if ((tm_now.tm_sec != lastSecond)
        && ((tm_now.tm_sec == 15) || (tm_now.tm_sec == 45))) {
      lastSecond = tm_now.tm_sec;
      updateStatusClients(STATUS_UPDATE_ERROR);
    }

  }

  // update LEDs
  blinkLeds();

}

void blinkLeds() {

  blinkWifiLed();
  blinkIrrigationPumpLed();
  blinkWellPumpLed();

}

void blinkWifiLed() {
  
  if (wifiStatus == WIFI_STATUS_DISCONNECTED) {
      digitalWrite(GPIO_WIFI_LED, HIGH);
  } else if (wifiStatus == WIFI_STATUS_CONNECTING) {
    if (interval % 2 == 0) { // blinking fast
      digitalWrite(GPIO_WIFI_LED, HIGH);
    } else {
      digitalWrite(GPIO_WIFI_LED, LOW);
    }
  } else if (wifiStatus == WIFI_STATUS_WAITING_FOR_NTP) {
    if (interval >> 3 == 0) { // blinking slow
      digitalWrite(GPIO_WIFI_LED, HIGH);
    } else {
      digitalWrite(GPIO_WIFI_LED, LOW);
    }
  } else if (wifiStatus == WIFI_STATUS_NTP_ACTIVE) {
    digitalWrite(GPIO_WIFI_LED, LOW);
  }

}

void printTime(time_t time) {

  tm tmp_tm;
  localtime_r(&time, &tmp_tm);          // converts epoch time to tm structure

  Serial.printf("%04u-%02u-%02u %02u:%02u:%02u (day: %u, daylight-saving: %u)\n",
      tmp_tm.tm_year + 1900,            // years since 1900
      tmp_tm.tm_mon + 1,                // January = 0 (!)
      tmp_tm.tm_mday,                   // day of month
      tmp_tm.tm_hour,                   // hours since midnight 0-23
      tmp_tm.tm_min,                    // minutes after the hour 0-59
      tmp_tm.tm_sec,                    // seconds after the minute 0-59
      tmp_tm.tm_wday,                   // days since Sunday 0-6
      tmp_tm.tm_isdst);                 // Daylight Saving Time flag

}

void setError(const char *format, ...) {

  if (error != NULL) {
    return;
  }

  error = new char[MAX_ERROR_LENGTH];
  va_list arg;
  va_start(arg, format);
  vsnprintf(error, MAX_ERROR_LENGTH, format, arg);
  va_end(arg);

  Serial.println(error);

  updateStatusClients(STATUS_UPDATE_ERROR);

}
