#!/usr/bin/env bash
#
# One-time setup for headless builds of IrrigationManagementESP.
#
# Three modes:
#   1) --online    Install arduino-cli (via brew or upstream installer) and the
#                  pinned ESP32 core from Espressif's index. Default if no
#                  vendor/ snapshot is present.
#   2) --from-vendor  Restore arduino-cli + ESP32 core from a tarball stored
#                  under vendor/. No internet needed. Use this on a fresh
#                  machine in 5+ years if upstream is gone.
#   3) --snapshot  After a successful --online install, create a vendor/
#                  tarball you can archive (GitHub release, external drive).
#
# All Arduino state (cores, packages) is kept LOCAL to this project under
# .arduino-data/ — your global ArduinoIDE installation is untouched.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_NAME="IrrigationManagementESP"
# Toolchain lives OUTSIDE the sketch dir — some cores ship source files with
# characters Arduino rejects (e.g. BearSSL's chain-ec+rsa.h on ESP8266) and
# ArduinoIDE 2.x scans the sketch dir recursively, including hidden folders.
ARDUINO_DATA="$HOME/Library/Arduino15-$PROJECT_NAME"
ARDUINO_CONFIG="$SCRIPT_DIR/.arduino-cli.yaml"
VENDOR_DIR="$SCRIPT_DIR/vendor"
VERSIONS_FILE="$SCRIPT_DIR/.versions.txt"

# Pinned versions — keep in sync with .versions.txt
ARDUINO_CLI_VERSION="1.1.1"
ESP32_CORE_VERSION="3.2.1"
ESP32_CORE_INDEX="https://espressif.github.io/arduino-esp32/package_esp32_index.json"

MODE="auto"
for arg in "$@"; do
  case "$arg" in
    --online)       MODE="online" ;;
    --from-vendor)  MODE="from-vendor" ;;
    --snapshot)     MODE="snapshot" ;;
    -h|--help)      sed -n '2,18p' "$0"; exit 0 ;;
    *) echo "Unknown option: $arg" >&2; exit 2 ;;
  esac
done

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
err() { printf '\033[1;31m!!\033[0m %s\n' "$*" >&2; }

write_arduino_config() {
  mkdir -p "$ARDUINO_DATA"
  cat > "$ARDUINO_CONFIG" <<EOF
# Generated by setup-toolchain.sh — keeps this project's Arduino state local.
directories:
  data: $ARDUINO_DATA
  downloads: $ARDUINO_DATA/staging
  user: $ARDUINO_DATA/user
board_manager:
  additional_urls:
    - $ESP32_CORE_INDEX
EOF
}

install_arduino_cli() {
  if command -v arduino-cli >/dev/null 2>&1; then
    log "arduino-cli already installed: $(arduino-cli version | head -1)"
    return
  fi
  log "Installing arduino-cli..."
  if command -v brew >/dev/null 2>&1; then
    brew install arduino-cli
  else
    mkdir -p "$HOME/.local/bin"
    curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh \
      | BINDIR="$HOME/.local/bin" sh
    export PATH="$HOME/.local/bin:$PATH"
    err "Add \$HOME/.local/bin to your PATH."
  fi
}

install_core_online() {
  log "Updating board index..."
  arduino-cli --config-file "$ARDUINO_CONFIG" core update-index
  log "Installing esp32:esp32@$ESP32_CORE_VERSION (downloads ~250 MB toolchain)..."
  arduino-cli --config-file "$ARDUINO_CONFIG" core install "esp32:esp32@$ESP32_CORE_VERSION"
}

restore_from_vendor() {
  local tarball="$VENDOR_DIR/esp32-core-${ESP32_CORE_VERSION}.tar.gz"
  if [[ ! -f "$tarball" ]]; then
    err "Vendor tarball not found: $tarball"
    err "On a machine with internet, run: ./setup-toolchain.sh --online && ./setup-toolchain.sh --snapshot"
    exit 1
  fi
  log "Restoring ESP32 core from $tarball..."
  mkdir -p "$ARDUINO_DATA/packages"
  tar -xzf "$tarball" -C "$ARDUINO_DATA/packages"
  log "Done. Verify with: arduino-cli --config-file $ARDUINO_CONFIG core list"
}

snapshot_vendor() {
  if ! arduino-cli --config-file "$ARDUINO_CONFIG" core list 2>/dev/null \
       | awk '{print $1}' | grep -qx 'esp32:esp32'; then
    err "Nothing to snapshot — run --online first."
    exit 1
  fi
  mkdir -p "$VENDOR_DIR"
  local tarball="$VENDOR_DIR/esp32-core-${ESP32_CORE_VERSION}.tar.gz"
  log "Creating $tarball (this is large; archive it externally)..."
  tar -czf "$tarball" -C "$ARDUINO_DATA/packages" esp32
  log "Snapshot complete: $(du -h "$tarball" | awk '{print $1}')"
  log "Recommended: upload to a GitHub release on this repo, then commit the URL/hash to .versions.txt."
}

write_arduino_config

case "$MODE" in
  online|auto)
    install_arduino_cli
    install_core_online ;;
  from-vendor)
    install_arduino_cli
    restore_from_vendor ;;
  snapshot)
    snapshot_vendor ;;
esac

log "Toolchain ready. Next: ./build-firmware.sh"
